config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   resources :posts
#   resources :articles
#   resources :blogs
# 	resources :domains  
	resources :topics
# 	resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < activateRecord::Base
	validates :title, presence: true, length: {minimum: 4, maximum: 20}
	validates :description, presence: true, length: {minimum: 4, maximum: 300}
	
	
end	

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :title, presence: true, length: {minimum:4, maximum:30}
	validates :description, presence: true, length: {minimum:3, maximum: 300} 
	
	
end	

app/models/domain.rb
class Domain < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 3, maximum: 36}	
	validates :description, presence: true, length: {minimum: 3, maximum: 300}
end	

app/models/list.rb
class List < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 2, maximum: 300}	
	validates :description, presence: true, length: {minimum: 2, maximum: 300}
end	

app/models/topic.rb
class Topic < ActiveRecord::Base
	
	validates :title, presence: true, length: {minimum: 2, maximum: 36}
	validates :description, presence: true, length: {minimum: 2, maximum: 300}
	
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticleController < ApplicationConroller

	def new	
		

			
	end	
	

	
	
end	

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def new
		
		@blog = Blog.new
		
	end	
	
	def create
		@blog = Blog.new(blog_params)
		@blog.save
		redirect_to blogs_path(@blog)
		
	end	
	
	private
	def blog_params
	
		params.require(:blog).permit(:title, :description)
	
	end	
end	

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

	def new 
		@domain = Domain.new
		
	end
# create action	
	def create
# a new or usualy way
	@domain = Domain.new(domains_params)
		if @domain.save
			flash[:notice] = "Your Post is succefully saved"
			redirect_to domain_path(@domain)
			
		else
			render 'new'
		
		end	

#old way to save to DB
# 		@domain = Domain.new(params_domain)
# 		
# 		@domain.save
# 		redirect_to domain_path(@domain)
	
	end	
# a private method 
	private
	
	def domains_params
		
		params.require(:domain).permit(:title, :description)
		
	end	
# show action	
	def show
		@domain = Domain.find(params[:id])	
	end	
	


	
			
end	

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	# actions
	
# 	def index 
# 		
# 	end	
	def new 
		@list = List.new
		
	end
	
	def show
		@list = List.find(params[:id])	
	end
	
	def update
	
		@list = List.find(params[:id])
			if @list.update(lists_params)
				flash[:notice] = "Your post are seccefully UPDATED"
				redirect_to list_path(@list)
			else render 'edit' 
			end
					
		
	end		 
	
	def create
		@list = List.new(lists_params)
			if @list.save
				flash[:notice] = "Your post are seccefully created"
				redirect_to list_path(@list)
			else render 'new'
			end	
						
	end			
	
	private
	def lists_params
		params.require(:list).permit(:title, :description)	
	end	
	
	
end	

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

# index action
	def index
		@topics = Topic.all
	end	
# new action
	def new
		@topic = Topic.new
	end	

# edit action
	def edit
		
		@topic = Topic.find(params[:id])
		
	end	

# update action
	def update
		@topic = Topic.find(params[:id])
		if @topic.update(topic_params)
			flash[:notice] = "Topic seccessufully Updatde"
			redirect_to topic_path(@topic)
		else render 'edit'
		end
			
	end	
	
# create action
	def create	
		@topic = Topic.new(topic_params) 
			if @topic.save
				flash[:notice] = "Topic seccessufully created"
				redirect_to topic_path(@topic)
			else 
				render 'new'		
			end						
	end	

# show action 
	def show
		@topic = Topic.find(params[:id])
	end	

# private method
	private
	def topic_params
		params.require(:topic).permit(:title, :description)
	end	 	


end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<h1>hello new article</h1>
<%= form_for @post do |f|
	@article = Article.new

app/views/blogs/new.html.erb
<h1>create a new blogs</h1>
<%= form_for @blog do |f|%>
	<p>

	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>
	<!-- description text_area 	 -->
	<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/domains/new.html.erb
<h1>Create a new post domain</h1>
<!-- show the errrors message to the users -->

	<% if @domain.errors.any? %>
	
		<ul>
			<% @domain.errors.full_messages.each do |msg| %>
			<li>
					<%= msg %>
			</li>
		</ul>	
	<% end %>
	<% end %>


<!-- Form -->
<%= form_for @domain do |f| %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>	
	<p>
		<%= f.submit %>
	</p>	
	
<% end %>	

app/views/domains/show.html.erb
<h1>Show saved posts</h1>
<p>
Title: <%= @domain.title %>
</p>


<p>
	Description: <%= @domain.description %>
</p>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |name, msg| %>
  	<li>
  	<%= msg %>
  	<li>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<h1>NEW action</h1>
<!-- if not meet the validates show this message bellow -->
	<% if @list.errors.any? %>
		
		<% @list.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			
		<% end %>
	<% end %>

<!-- form -->
	<%= form_for @list do |f| %>
		<p>
		<!-- title 		 -->
		<%= f.label :title %><br>
		<%= f.text_field :title %>
		</p>
		<p>
		<!-- description 		 -->
		<%= f.label :description %><br>
		<%= f.text_area :description %>
		</p>
		<p>
		<!-- submit 		 -->
		<%= f.submit %>
		</P>	
	<% end %>

app/views/lists/show.html.erb
<h1>Show action</h1>

<!-- form -->
	<%= form_for @list do |f| %>
		<p>
		<!-- title 		 -->
		<%= f.label :title %><br>
		<%= f.text_field :title %>
		</p>
		<p>
		<!-- description 		 -->
		<%= f.label :description %><br>
		<%= f.text_area :description %>
		</p>
		<p>
		<!-- submit 		 -->
		<%= f.submit %>
		</P>	
	<% end %>

app/views/topics/edit.html.erb
<h1>EDIT action Page</h1>
<!-- COPIED FROM new.html.erb -->

<!-- if any errors or not bypassing the Validates filters, show this !! -->
	<% if @topic.errors.any? %>
	<h2>sorry you can't create a Post, see why in list bellow !!</h2>
	<ul>
		<% @topic.errors.full_messages.each do |msg| %>
			
			<li>
				<%= msg %>
			</li>
		
		<% end %>
		
	</ul>	
	<% end %>	

<!-- form for new action page -->

	<%= form_for @topic do |f|%>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>
		
		<p>
			<%= f.label :description %><br>
			<%= f.text_area :description %>
		</p>
		
		<p>
			<%= f.submit %>
		</p>	
				
		
	<% end %>
<!-- 	link to index -->

<%= link_to"Back to all topics list", topics_path(@topic) %>

app/views/topics/index.html.erb
<h1>List of all topics </h1>
<!-- add link to create action (for create a new topic/post) -->
<p>
<%= link_to"Create a new topic", new_topic_path %>	
</p>

<!-- table to show all topics in DB -->
<table>
	<caption></caption>
	<thead>
		<tr>
			<th>Title</th>
			<th>description</th>
		</tr>
	</thead>
	<% @topics.each do |top| %>
	<tbody>		
		<tr>
			<td><%= top.title %></td>
			<td><%= top.description %></td>
			<td><%= link_to"Edit", edit_topic_path(top) %></td>
			<td><%= link_to"Show", topic_path(top)%> </td>
		</tr>
	</tbody>
	<% end %>

</table>

app/views/topics/new.html.erb
<h1>Page of NEW action</h1>
<!-- if any errors or not bypassing the Validates filters, show this !! -->
	<% if @topic.errors.any? %>
	<h2>sorry you can't create a Post, see why in list bellow !!</h2>
	<ul>
		<% @topic.errors.full_messages.each do |msg| %>
			
			<li>
				<%= msg %>
			</li>
		
		<% end %>
		
	</ul>	
	<% end %>	

<!-- form for new action page -->

	<%= form_for @topic do |f|%>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>
		
		<p>
			<%= f.label :description %><br>
			<%= f.text_area :description %>
		</p>
		
		<p>
			<%= f.submit %>
		</p>	
				
		
	<% end %>

app/views/topics/show.html.erb
<h1>SHOW action Page</h1>

<p>
Title: <%= @topic.title %>
</p>
<p>
Description: <%= @topic.description %>
</p>

<%= link_to"edit this topic", edit_topic_path(@topic) %> |


	<%= link_to"Back to all topics list", topics_path(@topic) %>